import React from "react";
import Head from "next/head";
import NavBar from "components/NavBar";
import Link from "next/link";
import { getAllDocs } from "@/lib/docs";

function Peacelab() {
    const courseBasePath = "peacelab/courses";

    const { beginner, intermediate, advanced } = getAllDocs();

    const length = Math.max(
        Object.keys(beginner).length,
        Object.keys(intermediate).length,
        Object.keys(advanced).length
    );

    return (
        <>
            <Head>
                <title>Peace Lab</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <NavBar />
            <div className='h-20'></div>
            <main className='w-full h-screen text-center'>
                <div className='w-full h-[5rem] text-center'>
                    <div className='max-w-[1240px] w-full h-full mx-auto p-2 flex justify-center items-center'>
                        <h1 className='my-8'>Peace Lab</h1>
                    </div>
                </div>

                <table className='table-auto mx-auto'>
                    <thead>
                        <tr>
                            <th>Beginner</th>
                            <th>Intermediate</th>
                            <th>Advanced (Coming soon)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {new Array(length).fill(0).map((_, key) => {
                            const [beginnerId, beginnerName] =
                                Object.entries(beginner)[key] || [];
                            const [intermediateId, intermediateName] =
                                Object.entries(intermediate)[key] ||
                                [];
                            const [advancedId, advancedName] =
                                Object.entries(advanced)[key] || [];
                            return (
                                <tr key={key}>
                                    <td>
                                        {beginnerId && (
                                            <Link
                                                href={`/${courseBasePath}/beginner/${beginnerId}`}>
                                                {beginnerName}
                                            </Link>
                                        )}
                                    </td>
                                    <td>
                                        {intermediateId && (
                                            <Link
                                                href={`/${courseBasePath}/intermediate/${intermediateId}`}>
                                                {intermediateName}
                                            </Link>
                                        )}
                                    </td>
                                    <td>
                                        {advancedId && (
                                            <Link
                                                href={`/${courseBasePath}/intermediate/${advancedId}`}>
                                                {advancedName}
                                            </Link>
                                        )}
                                    </td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </main>
        </>
    );
}

export default Peacelab;
